### ISSUE TITLE
StoryMap14: Layout of Infobox

### ISSUE THREAD

**Issue by danielabrandt** [geoadmin/web-storymaps#165]
Hi Marc,

could you make the text "bündig" in the Infobox and also have the layout of additional Info right (see screenshot)
![infoboxlayout](https://cloud.githubusercontent.com/assets/5592275/5933643/a74f91fe-a6c3-11e4-8cc4-2ae2461750b0.JPG)

**Comment by danielabrandt** [comment]
thx

**Comment by davidoesch** [comment]
While you are at it rename swisstopo to Federal office of topography swisstopo...
