### ISSUE TITLE
StoryMap14: Layout of the symbols (customer input)

### ISSUE THREAD

**Issue by danielabrandt** [geoadmin/web-storymaps#167]
Hi Marc,

Susanne saw the symbols, overall she is happy just some enhancements in the layout:

- - wäre es möglich die Umrandungen der Symbole (ausser bei Schwarz) grau oder deutlich dünner zu machen? Sie wirken etwas schwer, vorallem bei den oberen Zoomstufen / would it be possible to make the black line thinner or grey?
- das 5-Eck ist im Verhältnis zu den anderen Symbolen ein bisschen gross, geht es auch noch ein wenig kleiner? - the 5 Eck is a little bit too big in comparison to the other symbols, could you make it a little bit smaller
- es ist kein mouseover umgesetzt, sondern der Name erscheint beim Klick - könnte man dort das Attribut Sprachcode noch zeigen? - could you put in the attribute "Sprachcode" in too (I will get the translation from Susanne)?
- es ist gut, dass beim näher Zoomen die Namen dann direkt angezeigt werden - it is good that names are shown when you zoom in

No difference of Zoomlevels needed. Data can overall stay like this.

Thanks for providing a new testlink with the mentioned enhancements of the customer!

**Comment by davidoesch** [comment]
Mouseover with so many points you will get a nasty effect of tool tip coming up when you actually don't want it. Won't work on mobile neither. 

Furthermore try to keep it reusable... If it would have been done with a kml it is just standard

**Comment by danielabrandt** [comment]
Feedback von Susanne:

Dann lassen wir die Sprachen vorerst, im Prinzip hat Marc recht. Schauen wir dann wie die Legende aussieht. Ich bin eigentlich nur darauf gestossen, weil im Moment beim Tooltip noch ein Platzhalter steht.

Mouseover muss nicht sein. Ich denke, die Nutzer klicken ganz automatisch, so wie ich das auch gemacht habe. Und beim Zoomen kommen die Namen ja dann automatisch.
