### ISSUE TITLE
StoryMap2: KML without advertising

### ISSUE THREAD

**Issue by danielabrandt** [geoadmin/web-storymaps#190]
HI Marc,

concerning KML of StoryMap 2, could we remove the advertising at the end? David send me a link how we might do this:
http://stackoverflow.com/questions/13981310/embed-youtube-video-with-no-ads. Could you discuss with Arnaud, or another trainee how to best fix this situation for all KML in this StoryMap.

Thank you!

![kmlwith](https://cloud.githubusercontent.com/assets/5592275/7450434/2b2b8182-f245-11e4-9f87-d87e45d02649.JPG)

**Comment by ponceta** [comment]
Du musst den link zu den Youtube Videos ändern wie vorgeschlagen :

`If you play the video as a playlist and then single out that video you can get it without ads. Here is what I have done: //www.youtube.com/v/VIDEO_ID?playlist=VIDEO_ID&autoplay=1&rel=0`

für jedes youtube link z. B.

//www.youtube.com/embed/dnLuWVxzvok

//www.youtube.com/embed/dnLuWVxzvok?playlist=dnLuWVxzvok&autoplay=1&rel=0

**Comment by danielabrandt** [comment]
Ist ok now. thank you very much!
