### ISSUE TITLE
StoryMap 4 does not work

### ISSUE THREAD

**Issue by danielabrandt** [geoadmin/web-storymaps#205]
https://github.com/geoadmin/web-storymaps/pull/204

Salut Marc,

I just saw StoryMap 4 is not working:

http://storymaps.geo.admin.ch/storymaps/storymap4/?lang=de

StoryMap 3 is: http://storymaps.geo.admin.ch/storymaps/storymap3/?lang=de

Could you fix this ASAP, as a presentation is coming up,

Thanks,
Daniela

**Comment by danielabrandt** [comment]
Welche Quelle ?

Diese

https://data.geo.admin.ch/ch.bafu.hydroweb-messstationen_temperatur/ch.bafu.hydroweb-messstationen_temperatur_fr.json

oder 

http://www.hydrodaten.admin.ch/lhg/SMS.xml

Gruss


Marc

**Comment by danielabrandt** [comment]
Salut Ambrogio,

weisst du wieso die Quelle oder die Struktur der Quelle der Wassertemperaturen (10 Minütige Aktualisierung) sich geändert hat und wo sie jetzt ist, bzw. wer sie administriert und Marc Auskunft geben kann.

Merci,
Daniela

**Comment by AFoletti** [comment]
I'm sorry but I have absolutely no idea.
By looking at the proposed sources, the XML looks like the right place to look after the data, since the JSON only has basic class info

**Comment by danielabrandt** [comment]
thank you. See Email of Dave:

Wir sind daran  dies zu beheben

Offensichtlich hat sich das Datenlieferformat geändert- sind am abklären

Mfg

David


-----Ursprüngliche Nachricht-----
Von: Edith.Oosenbrug@bafu.admin.ch [mailto:Edith.Oosenbrug@bafu.admin.ch] 
Gesendet: Dienstag, 3. Mai 2016 17:55
An: Oesch David swisstopo <David.Oesch@swisstopo.ch>
Cc: Helbling Andreas Christian BAFU <andreas.helbling@bafu.admin.ch>; Eberhard Adrian BAFU <Adrian.Eberhard@bafu.admin.ch>
Betreff: WG: Die wärmsten Fliessgewässer der Schweiz

Lieber Dave
Da scheint etwas durcheinander gekommen zu sein. Gibt es generell Probleme mit den Storymaps oder hier besonders?
Danke fürs Anschauen und liebe Grüsse, Edith

***********************************************************************
Edith Oosenbrug
Leiterin des Dienstes Information
Eidgenössisches Departement für Umwelt, Verkehr, Energie und Kommunikation UVEK Bundesamt für Umwelt BAFU Abteilung Hydrologie
3003 Bern
Tel. +41 58 462 07 68
Fax +41 58 462 07 68
edith.oosenbrug@bafu.admin.ch
www.bafu.admin.ch/hydrologie 

Anwesend: Montag, Dienstag und Freitag



-----Ursprüngliche Nachricht-----
Von: Eberhard Adrian BAFU
Gesendet: Dienstag, 3. Mai 2016 11:10
An: Oosenbrug Edith BAFU <Edith.Oosenbrug@bafu.admin.ch>
Betreff: Die wärmsten Fliessgewässer der Schweiz

Hallo Edith

Wollte mal die storymap mit den Wassertemperaturen demonstrieren, aber die funktioniert nicht ....  :-(


http://storymaps.geo.admin.ch/storymaps/storymap4/?lang=de


ä Gruess/ EA

**Comment by danielabrandt** [comment]
additionally I just saw this: https://redmine.prod.bgdi.ch/issues/5142

**Comment by danielabrandt** [comment]
Email an Marc (09.05.16 / 10 Uhr): 

Salut Marc,

bezüglich: StoryMap4 https://github.com/geoadmin/web-storymaps/pull/205

die Quelle sollte laut Mario nicht geändert haben. Auch nicht in der Struktur:

https://s.geo.admin.ch/6bbfd3095a

Kannst du diese reparieren? Oder gibt es noch eine Frage an mich oder Mario, welcher mehr über die Daten weiss.

Gruss,
Daniela

**Comment by procrastinatio** [comment]
Waiting for https://jira.swisstopo.ch/secure/RapidBoard.jspa?rapidView=38&projectKey=BGDIINF_SB&view=planning&selectedIssue=BGDIINF_SB-209
