### ISSUE TITLE
StoryMap 13: Links to swisstopo page in 4 languages

### ISSUE THREAD

**Issue by danielabrandt** [geoadmin/web-storymaps#210]
Please Change links in Infobox (as written in Email from Karto on Monday):
http://storymaps.geo.admin.ch/storymaps/storymap13/?lang=de
 

In allen 4 Sprachen!

Neue Landeskarte der Schweiz: https://www.swisstopo.admin.ch/de/wissen-fakten/karten-und-mehr/neue-landeskarte.html

Blattübersicht NLK 1:25 000: https://s.geo.admin.ch/6ddd9427a2

Swisstopo Produkte: https://shop.swisstopo.admin.ch/de/products/maps/national/lk25

thanks!

**Comment by MartinaJoelle** [comment]
Can you check http://web-storymaps.dev.bgdi.ch/storymaps/storymap13/?lang=en

**Comment by danielabrandt** [comment]
Hi Martina,

perfect! I just tested it. Looks good.

thank you very much,
Daniela

PS: Can you deploy it?

**Comment by MartinaJoelle** [comment]
http://storymaps.geo.admin.ch/storymaps/storymap13/ wurde deployed
Kannst du den Link bitte überprüfen? Danke.

**Comment by danielabrandt** [comment]
Merci vielmals Euch beiden, tip top. Grosses Lob an Martina auch fürs Unterstützen von Marc und Marc für das Weitergeben des Wissens! Merci!
